import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import TopNav from '@/components/shared/TopNav'
import MainSection from '@/components/shared/MainSection'
import NewExpenseIcon from '@/components/shared/NewExpenseIcon'
import { ChartProvider } from '@/lib/contexts/ChartProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BrainBudget',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <ChartProvider>
        <html lang="en">
          <body className={inter.className}>
            <TopNav />
            <MainSection children={children} />
          </body>
        </html>
      </ChartProvider>
    </ClerkProvider>
  )
}
